name: CI

on:
  push:
    branches:
      - master

jobs:
  build-test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        php_version: [ "5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1" ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php_version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php_version }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run Tests
        run: make test
        env:
          API_BASE: ${{ secrets.API_BASE }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          SMARTPAY_SECRET_KEY: ${{ secrets.SMARTPAY_SECRET_KEY }}
          SMARTPAY_PUBLIC_KEY: ${{ secrets.SMARTPAY_PUBLIC_KEY }}
          SMARTPAY_API_PREFIX: ${{ secrets.SMARTPAY_API_PREFIX }}