name: CI

on:
  pull_request:

jobs:
  build-unit-test:
    strategy:
      matrix:
        php_version: [ 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php_version }}
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text --exclude-group integration
        env:
          XDEBUG_MODE: coverage